## NumPy 특징
- 과학기술 계산을 위한 라이브러리를 제공
- 벡터/행렬/배열 처리 및 연산, 난수 발생
- 파일관리(txt, csv 등 파일 읽기/쓰기)
- 리스트형 데이터와 유사하지만 numpy는 배열의 특징을 가짐
- 모든 원소는 동일한 자료형이어야 한다.
- 원소들 중 다른 자료형이 있다면 가장 큰 자료형으로 변경됨
- 계산 속도가 빠르다.
- 벡터 연산, 배열 인덱싱 등을 통해 질의 가능

In [4]:
import numpy as np

In [5]:
lst = [1, 2, 3, 4, 5, 6]
lst2 = []
for i in lst:
    lst2.append(i*2)
lst2

[2, 4, 6, 8, 10, 12]

In [8]:
arr_lst = np.array(lst)
print(arr_lst)

[1 2 3 4 5 6]


In [9]:
# numpy 연산

arr1 = np.array([1, 2, 3])
arr2 = np.array([10, 20, 30])

print(arr1 + arr2)
print(arr2 >= 20)

[11 22 33]
[False  True  True]


In [10]:
# 2차원 배열 구조
import pandas as pd

lst = [[0,0,1], [8,12,33]]
print(lst[0])
print(lst[1])

df = pd.DataFrame(lst)
print(df.shape)

[0, 0, 1]
[8, 12, 33]
(2, 3)


In [11]:
arr = np.array(lst)
print(lst)
print(arr)

[[0, 0, 1], [8, 12, 33]]
[[ 0  0  1]
 [ 8 12 33]]


In [13]:
print(len(lst))
print(len(arr))

print(len(lst[0]))
print(len(arr[0]))

2
2
3
3


In [15]:
lst = [[0,0,1,1], [8, 12, 33]]
arr = np.array(lst)
arr

C:\Users\김도연\AppData\Local\Temp/ipykernel_33624/2843499642.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  arr = np.array(lst)


array([list([0, 0, 1, 1]), list([8, 12, 33])], dtype=object)

In [16]:
# 3차원 배열
lst = [[[10, 20, 30]]]
arr = np.array(lst)
print(arr.shape)
print(arr)

(1, 1, 3)
[[[10 20 30]]]


In [18]:
lst=[[[10,20,30],[15, 25, 35]], [[1., 2., 3.],[12, 13., '15']]]
arr = np.array(lst)
print(arr.shape)
print(arr)

(2, 2, 3)
[[['10' '20' '30']
  ['15' '25' '35']]

 [['1.0' '2.0' '3.0']
  ['12' '13.0' '15']]]


In [21]:
from sys import getsizeof

a = 1;b = 1.;c = '1'

print(getsizeof(a))
print(getsizeof(b))
print(getsizeof(c))

28
24
50


In [22]:
# 배열구조 데이터 인덱싱

arr=np.array([10,20,30,40,50])
print(arr[0])
print(arr[-1])
print(arr[2])

10
50
30


In [28]:
arr = np.array([[10, 20, 30, 40, 50], [15, 25, 35, 45, 55]])
print(arr[0])       # 첫번쨰 행 전체
print(arr[-1])      # 마지막행 전체
print(arr[0, 0])    # 첫번쨰 행의 첫번쨰 열
print(arr[-1, 1])   # 마지막 행의 세번째 열


[10 20 30 40 50]
[15 25 35 45 55]
10
25


In [ ]:
# 3차원 배열의 인덱싱

arr = np.array([[[10,20,30],[15, 25, 35]], [[1., 2., 3.],[12, 13., 15]]])
print(arr.shape)
print(arr, '\n')

In [35]:
print(arr[0], '\n')
print(arr[-1], '\n')
print(arr[0,0], '\n')
print(arr[-1, 1], '\n')

[[10. 20. 30.]
 [15. 25. 35.]] 

[[ 1.  2.  3.]
 [12. 13. 15.]] 

[10. 20. 30.] 

[12. 13. 15.] 



In [36]:
# boolean 배열 방식을 이용한 인덱싱

arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
atf = np.array([True, False, True, False, True, False, True, False, True, False])
arr[atf]

array([0, 2, 4, 6, 8])

In [ ]:
# 배열생성/구조변경

In [40]:
arr = np.array([15, 25, 35, 45], dtype='f')
arr.dtype

dtype('float32')

In [41]:
arr[1] = 28
arr

array([15., 28., 35., 45.], dtype=float32)

In [44]:
arr = np.arange(1, 10 , 2)
arr.dtype

dtype('int32')

In [47]:
arr = np.logspace(0.1, 1, 10)
arr

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [48]:
arr = np.linspace(0, 100, 5)
arr

array([  0.,  25.,  50.,  75., 100.])

In [51]:
# 배열 데이터 변경

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

arr_res = arr.reshape(2, 5) # 배열 구조 변경 
arr_res

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [52]:
arr = np.arange(1, 51)
arr_res = arr.reshape(-1, 5)
arr_res

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [68]:
arr = np.arange(1, 55)
arr_res = arr.reshape(6, -1)
arr_res

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50, 51, 52, 53, 54]])

In [76]:
arr_res = arr.reshape(-1, 3, 6)
arr_res

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18]],

       [[19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36]],

       [[37, 38, 39, 40, 41, 42],
        [43, 44, 45, 46, 47, 48],
        [49, 50, 51, 52, 53, 54]]])

# 브로드캐스팅 & 마스킹
- 하나의 배열 or 요소가 어떤 특정 배열에 영향을 미칠 때 배열간의 형상을 맞추는 것을 브로드 캐스팅이라고 함

In [88]:
arr = np.arange(1, 101)
# arr
idx = arr%2==0

# print(arr[idx]
arr[idx] = 100
arr

array([  1, 100,   3, 100,   5, 100,   7, 100,   9, 100,  11, 100,  13,
       100,  15, 100,  17, 100,  19, 100,  21, 100,  23, 100,  25, 100,
        27, 100,  29, 100,  31, 100,  33, 100,  35, 100,  37, 100,  39,
       100,  41, 100,  43, 100,  45, 100,  47, 100,  49, 100,  51, 100,
        53, 100,  55, 100,  57, 100,  59, 100,  61, 100,  63, 100,  65,
       100,  67, 100,  69, 100,  71, 100,  73, 100,  75, 100,  77, 100,
        79, 100,  81, 100,  83, 100,  85, 100,  87, 100,  89, 100,  91,
       100,  93, 100,  95, 100,  97, 100,  99, 100])

# Numpy에서 파일 읽고 쓰기

In [1]:
with open('c:/pythonworkspace/multi/0729/data/test.txt', encoding = 'utf-8') as f:
    csv_data = []
    for line in f.readlines():
        csv_data.append(line.split(','))
print('csv_data', '\n', csv_data)

csv_data 
 [['a', '10\n'], ['b', '25\n'], ['c', '48\n'], ['d', '55\n'], ['e', '84\n'], ['f', '55\n'], ['g', '88']]


In [93]:
df = pd.read_csv('c:/pythonworkspace/multi/0729/data/test.txt', encoding='utf-8', names=['이름', '값'])
df

이름   값
0  a  10
1  b  25
2  c  48
3  d  55
4  e  84
5  f  55
6  g  88

In [95]:
np_data = np.loadtxt('c:/pythonworkspace/multi/0729/data/test.txt', dtype = 'str' ,delimiter=',')
np_da

array([['a', '10'],
       ['b', '25'],
       ['c', '48'],
       ['d', '55'],
       ['e', '84'],
       ['f', '55'],
       ['g', '88']], dtype='<U2')

# NaN 변경하기

In [97]:
arr = np.array([5, 6, np.NAN])
arr.dtype

dtype('float64')

In [98]:
np.isnan(arr)

array([False, False,  True])

In [100]:
np.nan_to_num(arr)

array([5., 6., 0.])

In [101]:
np.nanmean(arr)

5.5

In [109]:
arr[np.isnan(arr)] = np.nanmean(arr)
arr

array([5. , 6. , 5.5])

# 행렬 데이터의 결합, concatenate 함수

In [121]:
arr1 = np.random.randint(10, size=(2, 3))
arr2 = np.random.randint(10, size=(3, 2))
arr3 = np.random.randint(10, size=(3, 3))

print(arr1)
print(arr2)
print(arr3)

[[9 1 8]
 [1 7 4]]
[[8 4]
 [0 9]
 [7 4]]
[[7 5 7]
 [4 0 1]
 [4 3 3]]


concatenate : 기본 세로결합
- np.concatenate((a, b))

In [122]:
np.concatenate((arr2, arr3), axis=1)

array([[8, 4, 7, 5, 7],
       [0, 9, 4, 0, 1],
       [7, 4, 4, 3, 3]])